[config]
reload_apps = true

[templates.quickshell]
input_path = "~/.config/quickshell/colors.json.template"
output_path = "~/.config/quickshell/qs_colors.json"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty-colors.conf.template"
output_path = "~/.config/kitty/kitty-matugen-colors.conf"

[templates.neovim]
input_path = "~/.config/matugen/templates/nvim-colors.lua.template"
output_path = "~/.config/nvim/matugen_colors.lua"

[templates.cava]
input_path = "~/.config/matugen/templates/cava-colors.ini.template"
output_path = "~/.config/cava/colors"

[templates.swayosd]
input_path = "~/.config/matugen/templates/swayosd.css.template"
output_path = "~/.config/swayosd/style.css"

[templates.swaync]
input_path = "~/.config/matugen/templates/swaync.css.template"
output_path = "~/.config/swaync/style.css"

[templates.rofi]
input_path = "~/.config/matugen/templates/rofi.rasi.template"
output_path = "~/.config/rofi/theme.rasi"

[templates.ambxst]
input_path = "~/.config/matugen/templates/ambxst-colors.json"
output_path = "~/.cache/ambxst/colors.json"

[config.custom_colors.red]
color = "#FF0000"
blend = true

[config.custom_colors.green]
color = "#00FF00"
blend = true

[config.custom_colors.yellow]
color = "#FFFF00"
blend = true

[config.custom_colors.blue]
color = "#0000FF"
blend = true

[config.custom_colors.magenta]
color = "#FF00FF"
blend = true

[config.custom_colors.cyan]
color = "#00FFFF"
blend = true

[config.custom_colors.white]
color = "#FFFFFF"
blend = true

