source = $HOME/.config/hypr/config/variables.conf

# FLOATING WINDOW RULES
windowrule = float on, match:class ^(xdg-desktop-portal-gtk)$
windowrule = float on, match:class ^($terminal)$, match:title ^(top)$
windowrule = float on, match:class ^($terminal)$, match:title ^(btm)$
windowrule = float on, match:class ^($terminal)$, match:title ^(htop)$
windowrule = float on, match:class ^(thunar)$, match:title ^(Rename.*)$
windowrule = float on, match:class ^(Thunar)$, match:title ^(Rename.*)$
windowrule = float on, match:class ^(org.gnome.FileRoller)$
windowrule = float on, match:class ^(qt5ct)$
windowrule = float on, match:class ^(qt6ct)$
windowrule = float on, match:class ^(nwg-look)$
windowrule = float on, match:class ^(nwg-displays)$
windowrule = float on, match:class ^(org.pulseaudio.pavucontrol)$
windowrule = float on, match:class ^(blueman-manager)$
windowrule = float on, match:class ^(nm-connection-editor)$
windowrule = float on, match:class ^(org.Waytrogen.Waytrogen)$
windowrule = float on, match:class ^(waytrogen)$
windowrule = float on, match:class ^(com.github.unrud.VideoDownloader)$
windowrule = float on, match:class ^(com.interversehq.qView)$
