require("config/variables")

hl.window_rule({ match = {class = fileManager}, match = {title = "Rename.*"}, float = true})
hl.window_rule({ match = {class = "nwg-look"}, float = true})
hl.window_rule({ match = {class = "nwg-displays"}, float = true})
hl.window_rule({ match = {class = "org.pulseaudio.pavucontrol"}, float = true})
hl.window_rule({ match = {class = "blueman-manager"}, float = true})
hl.window_rule({ match = {class = "nm-connection-editor"}, float = true})
hl.window_rule({ match = {class = "nm-connection-editor"}, float = true})
hl.window_rule({ match = {class = "Bitwarden"}, float = true})