# APPLICATION KEYBINDINGS

bind = $mainMod, G, exec, godot
bind = $mainMod, G, exec, github-desktop fullscreen 0 
bind = $mainMod, C, exec, codium
bind = $mainMod, RETURN, exec, $terminal
bind = $mainMod SHIFT, RETURN, exec, [float; size 800 450; center] $terminal
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, B, exec, $browser
bind = $mainMod, A, exec, $launcher open
bind = $mainMod SHIFT, A, exec, $launcher deeplink vicinae://launch/clipboard/history
bind = $mainMod, N, exec, swaync-client -t
bind = $mainMod, Escape, exec, pgrep wlogout || wlogout -b 2
bind = $mainMod SHIFT, P, exec, hyprpicker -a
bind = $mainMod, W, exec, skwd wall toggle
bind = $mainMod ALT, W, exec, pgrep -x waybar >/de/null && killall waybar || waybar &
bind = $mainMod ALT, B, exec, bongocat -c ~/.config/bongocat/bongo.conf --toggle
bind = $mainMod ALT, N, exec, ~/.config/scripts/restart-swaync.sh
bind = $mainMod, O, exec, hyprlock
bind = $mainMod, V, exec, $launcher deeplink vicinae://extensions/vicinae/core/search-emojis
bind = $mainMod, Y, exec, bash ~/.config/scripts/quickshell/qs_manager.sh toggle monitors
bind = $mainMod, T, exec, bash ~/.config/scripts/quickshell/qs_manager.sh toggle focustime