-- Wallust generated colors for Hyprland 0.55+ Lua config
-- Do not edit directly — regenerated by: wallust run <image>

colors = {
  background = "rgb(1C1C18)",
  foreground = "rgb(ABABAB)",
  color0 = "rgb(4E4D47)",
  color1 = "rgb(B3B098)",
  color2 = "rgb(A48263)",
  color3 = "rgb(768A79)",
  color4 = "rgb(7B6756)",
  color5 = "rgb(596C60)",
  color6 = "rgb(434343)",
  color7 = "rgb(7F7F7F)",
  color8 = "rgb(595959)",
  color9 = "rgb(EFEBCA)",
  color10 = "rgb(CD9A6D)",
  color11 = "rgb(749478)",
  color12 = "rgb(927560)",
  color13 = "rgb(647D6C)",
  color14 = "rgb(464646)",
  color15 = "rgb(7F7F7F)"
}

return colors