-- Wallust generated colors for Hyprland 0.55+ Lua config
-- Do not edit directly — regenerated by: wallust run <image>

colors = {
  background = "rgb(171008)",
  foreground = "rgb(ACB1AC)",
  color0 = "rgb(463D36)",
  color1 = "rgb(927E6A)",
  color2 = "rgb(907B6E)",
  color3 = "rgb(81786B)",
  color4 = "rgb(6C675E)",
  color5 = "rgb(595A50)",
  color6 = "rgb(454B45)",
  color7 = "rgb(808781)",
  color8 = "rgb(5A5E5A)",
  color9 = "rgb(AB8C6C)",
  color10 = "rgb(9A7861)",
  color11 = "rgb(887A66)",
  color12 = "rgb(7C776A)",
  color13 = "rgb(636557)",
  color14 = "rgb(485248)",
  color15 = "rgb(808781)"
}

return colors