# HYPRLAND WINDOW RULES CONFIGURATION

source = $HOME/.config/hypr/rules/general.conf
source = $HOME/.config/hypr/rules/floating.conf
source = $HOME/.config/hypr/rules/dialogs.conf
source = $HOME/.config/hypr/rules/media.conf
source = $HOME/.config/hypr/rules/opacity.conf
source = $HOME/.config/hypr/rules/layers.conf


windowrule = workspace 8, fullscreen on, match:class ^(GitHub Desktop)$
windowrule = workspace 9, fullscreen on, match:class ^(fdm)$
windowrule = workspace 10, fullscreen on, match:class ^(Spotify)$
windowrule = fullscreen on, match:class ^(looking-glass-client)$

windowrule = opacity 0.9 0.8, match:class ^(codium)$

workspace = special:magic, on-created-empty:discord

windowrule {
    name = "master_rule"
    match:title = ^(qs-master)$
    float = on
    no_shadow = on
    no_initial_focus = on
    no_blur = on
    border_size = 0
    workspace = special:qs_hidden silent
}