-- Wallust generated colors for Hyprland 0.55+ Lua config
-- Do not edit directly — regenerated by: wallust run <image>

colors = {
  background = "rgb(1A150B)",
  foreground = "rgb(A9ACB2)",
  color0 = "rgb(4B4438)",
  color1 = "rgb(BFA56B)",
  color2 = "rgb(B5745E)",
  color3 = "rgb(6E81AB)",
  color4 = "rgb(997A8E)",
  color5 = "rgb(606E90)",
  color6 = "rgb(3F444D)",
  color7 = "rgb(7C8088)",
  color8 = "rgb(56595F)",
  color9 = "rgb(FFDC8F)",
  color10 = "rgb(EC9173)",
  color11 = "rgb(88A3DE)",
  color12 = "rgb(A46E91)",
  color13 = "rgb(6C7FAE)",
  color14 = "rgb(414754)",
  color15 = "rgb(7C8088)"
}

return colors