# HYPRLAND WINDOW RULES CONFIGURATION

source = $HOME/.config/hypr/rules/general.conf
source = $HOME/.config/hypr/rules/floating.conf
source = $HOME/.config/hypr/rules/dialogs.conf
source = $HOME/.config/hypr/rules/media.conf
source = $HOME/.config/hypr/rules/opacity.conf
source = $HOME/.config/hypr/rules/layers.conf


windowrule = workspace 6, fullscreen on, match:class ^(spotify)$
windowrule = workspace 8, fullscreen on, match:class ^(GitHub Desktop)$
windowrule = workspace 9, fullscreen on, match:class ^(fdm)$

workspace = special:magic, on-created-empty:discord

windowrule {
    name = "master_rule"
    match:title = ^(qs-master)$
    float = on
    pin = on
    no_shadow = on
    no_initial_focus = on
    no_blur = on
    move = 100000 100000
    border_size = 0
}
