-- Generated by nwg-displays on 2026-08-12 at 15:09:14. Do not edit manually.

hl.monitor({
    output = "DP-1",
    mode = "2560x1440@180.0",
    position = "3073x833",
    scale = 1.0
})
hl.monitor({
    output = "DP-2",
    mode = "1920x1080@180.0",
    position = "1993x503",
    scale = 1,
    transform = 1
})
