-- Generated by nwg-displays on 2026-05-24 at 16:35:34. Do not edit manually.

hl.monitor({
    output = "DP-1",
    mode = "2560x1440@180.0",
    position = "6332x2744",
    scale = 1.0
})
hl.monitor({
    output = "DP-2",
    mode = "1920x1080@180.0",
    position = "5252x2461",
    scale = 1.0,
    transform = 1
})
