hl.on("hyprland.start", function()
    hl.exec_cmd("ambxst")
    hl.exec_cmd("sleep 1 && ambxst run lockscreen")
    hl.exec_cmd("sunsetr")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("spotify")
    hl.exec_cmd("steam -silent &")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &")
    hl.exec_cmd("udiskie")
    hl.exec_cmd("easyeffects --gapplication-service")
    hl.exec_cmd("gnome-keyring-daemon --start --components=secrets")
    hl.exec_cmd(os.getenv("HOME") .. "/.config/scripts/theme/theme-sync.sh")
    hl.exec_cmd(os.getenv("HOME") .. "/.config/scripts/theme/wofi-colors.sh")
    hl.exec_cmd(os.getenv("HOME") .. "/.config/scripts/lib/color-utils.sh")
    hl.exec_cmd(os.getenv("HOME") .. "/.config/scripts/lib/common.sh")
    hl.exec_cmd("spicetify apply")
    hl.exec_cmd("vicinae server")
    hl.exec_cmd("quickshell -p ~/.config/quickshell/Main.qml")
    hl.exec_cmd(os.getenv("HOME") .. "/.config/scripts/quickshell/init.sh")
    hl.exec_cmd("python3 ~/.config/quickshell/focustime/focus_daemon.py &")
    hl.exec_cmd("systemctl --user start skwd-daemon")
    hl.exec_cmd("ollama")
    hl.exec_cmd("sunshine")
    hl.exec_cmd("tailscale up")
    hl.exec_cmd("zapzap")
    hl.exec_cmd("waybound --config ~/.config/waybound/waybound.toml")
    --hl.exec_cmd("hyprctl setcursor Vimix 32")
    hl.exec_cmd("bash ~/.config/scripts/system/terminal-start.sh")
    hl.exec_cmd("sleep 1 && hyprctl dispatch 'hl.dsp.focus({workspace = 6})'") 
    hl.exec_cmd("sleep 2 && hyprctl dispatch 'hl.dsp.focus({workspace = 1})'") 
end)