# AUTOSTART APPLICATIONS

exec-once = sunsetr
exec-once = awww-daemon
exec-once = [workspace 6; silent; fullscreen] spotify
exec-once = steam -silent & 
exec-once = hyprswitch init &
exec-once = waybar
exec-once = hypridle
exec-once = hyprpolkitagent
exec-once = udiskie
exec-once = swaync
exec-once = easyeffects --gapplication-service
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = hyprswitch init --show-title --size-factor 5 --workspaces-per-row 4 --custom-css $configDir/hyprswitch.css
exec-once = ~/.config/scripts/theme/theme-sync.sh
exec-once = ~/.config/scripts/theme/wofi-colors.sh
exec-once = ~/.config/scripts/lib/color-utils.sh
exec-once = ~/.config/scripts/lib/common.sh
exec-once = hyprlock
exec-once = spicetify apply
exec-once = vicinae server
exec-once = hyprctl dispatch exec "[workspace 10; silent; fullscreen] ghostty -e cmatrix"
exec-once = hyprctl dispatch workspace 1 
exec-once = quickshell -p ~/.config/quickshell/wallpaper/daemon.qml
exec-once = quickshell -p ~/.config/quickshell/Main.qml
exec-once = ~/.config/scripts/quickshell/init.sh
exec-once = python3 ~/.config/quickshell/focustime/focus_daemon.py &

