# AUTOSTART APPLICATIONS

exec-once = ambxst && sleep 2
exec-once = sunsetr
exec-once = awww-daemon
exec-once = [workspace 10; silent; fullscreen] spotify
exec-once = steam -silent & 
exec-once = hypridle
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
exec-once = udiskie
exec-once = easyeffects --gapplication-service
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = ~/.config/scripts/theme/theme-sync.sh
exec-once = ~/.config/scripts/theme/wofi-colors.sh
exec-once = ~/.config/scripts/lib/color-utils.sh
exec-once = ~/.config/scripts/lib/common.sh
exec-once = spicetify apply
exec-once = vicinae server
exec-once = hyprctl dispatch exec "[workspace 6] ghostty -e pipes-rs -f 45 -k heavy,light -r 0.6"
exec-once = hyprctl dispatch workspace 6 && sleep 0.2 && hyprctl dispatch fullscreen
exec-once = sleep 0.2 && hyprctl dispatch workspace previous
exec-once = quickshell -p ~/.config/quickshell/Main.qml
exec-once = ~/.config/scripts/quickshell/init.sh
exec-once = python3 ~/.config/quickshell/focustime/focus_daemon.py &
exec-once = systemctl --user start skwd-daemon
exec-once = ollama
exec-once = waybound --config ~/.config/waybound/waybound.toml
exec-once = sunshine
exec-once = tailscale up
exec-once = sh -c 'for i in $(seq 1 30); do ambxst run lockscreen && exit 0; sleep 0.25; done'
