# Hyprland with colors from wallust
# You can use this template by adding the following to wallust.toml:
# hypr = { src = "hyprland.conf", dst = "~/.config/hypr/colors.conf" }
# and then on hyprland.conf:
# source = ~/.config/hypr/colors.conf

general {
    col.active_border = rgb(7F75AC) rgb(E8232A) rgb(B06279) rgb(688BC4) rgb(826870)
    col.inactive_border = rgba(070707ee)
}
