hl.config({
    general = {
        col = {
            active_border = { colors = { "rgb(E03421)", "rgb(A1707A)", "rgb(AA7307)", "rgb(DBB29C)", "rgb(8C633B)" } },
            inactive_border = "rgba(0E0100ee)",
        },
    },
})